CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS raw_tmo;
CREATE SCHEMA IF NOT EXISTS stg_tmo; 
CREATE SCHEMA IF NOT EXISTS cur_tmo; 

-- create admin role
CREATE ROLE admin WITH CREATEDB CREATEROLE;

-- grant admin role to the login user
GRANT admin TO "KerbIntadmin";


GRANT ALL ON SCHEMA raw_tmo TO admin;
GRANT ALL ON SCHEMA stg_tmo TO admin;
GRANT ALL ON SCHEMA cur_tmo TO admin;

GRANT USAGE, CREATE ON SCHEMA raw_tmo TO admin;
GRANT USAGE, CREATE ON SCHEMA stg_tmo TO admin;
GRANT USAGE, CREATE ON SCHEMA cur_tmo TO admin;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA raw_tmo GRANT ALL ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA stg_tmo GRANT ALL ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA cur_tmo GRANT ALL ON TABLES TO admin;